### PR TITLE
Don't add jacoco tasks for ignored build variants

### LINKED ISSUE #67: excluded variants break build
The plugin adds dependencies for tasks of build types which are excluded and therefore not found.

```gradle
android {
    ...
    variantFilter { variant ->
        if (variant.name == "debug") {
            variant.setIgnore(true)
        }
    }
}
```

Results in:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:jacocoTestReportDebug'.
> Task with path 'testDebugUnitTest' not found in project ':app'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

### PR DESCRIPTION
**Pull request by passsy**
Fixes #67

The new implementation uses `android.libraryVariants` or `android.applicationVariants` instead of iterating manually over buildTypes and flavors. The bug is fixed because ignored variants are not included.

### CODE REVIEW

File: src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy [hunk 1]
```diff
@@ -21,9 +26,45 @@ final class ProjectHelper {
...
+                def androidMock = new MockFor(LibraryExtension)
+                def buildTypesMock = ["debug", "release"].collect { bt ->
+                    def type = new MockFor(BuildType)
+                    type.metaClass.getName = { bt }
+                    type
+                }
+                androidMock.metaClass.getBuildTypes = { buildTypesMock }
+                def appVariants = buildTypesMock.collect { bt ->
+                    def variant = new MockFor(BaseVariant)
+                    variant.metaClass.getFlavorName = { null }
```
Comment (vanniktech) [inline src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy]: do we need to do this?

File: src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy [hunk 2]
```diff
@@ -21,9 +26,45 @@ final class ProjectHelper {
...
+                def androidMock = new MockFor(AppExtension)
+                def buildTypesMock = ["debug", "release"].collect { bt ->
+                    def type = new MockFor(BuildType)
+                    type.metaClass.getName = { bt }
+                    type
+                }
+                androidMock.metaClass.getBuildTypes = { buildTypesMock }
+                def appVariants = buildTypesMock.collect { bt ->
+                    def variant = new MockFor(BaseVariant)
+                    variant.metaClass.getFlavorName = { null }
```
Comment (vanniktech) [inline src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy]: do we need to do this?

File: src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy [hunk 3]
```diff
@@ -21,9 +26,45 @@ final class ProjectHelper {
...
+                    variant.metaClass.getBuildType = { bt }
+                    variant
+                }
+                androidMock.metaClass.getApplicationVariants = { appVariants }
+                androidMock.metaClass.testOptions = null
+                project.metaClass.android = androidMock
+                // fake all with each
```
Comment (vanniktech) [inline src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy]: Can you transform it to a sentence?

File: src/main/groovy/com/vanniktech/android/junit/jacoco/Generation.groovy [hunk 4]
```diff
@@ -84,65 +86,69 @@ class Generation implements Plugin<Project> {
...
+
+                if (productFlavorName) {
+                    coverageSourceDirs.add("src/$productFlavorName/java")
                 }
 
-                subProject.check.dependsOn "${taskName}"
+                additionalSourceDirs = subProject.files(coverageSourceDirs)
+                sourceDirectories = subProject.files(coverageSourceDirs)
+                executionData =
+                        subProject.files("${subProject.buildDir}/jacoco/${testTaskName}.exec")
```
Comment (vanniktech) [inline src/main/groovy/com/vanniktech/android/junit/jacoco/Generation.groovy]: can you squeeze it into one line?

File: src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy (hunk 1 above)
Comment (passsy) [inline src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy]: Actually not, I just wanted to be explicit. It is required to be `null`

Comment (vanniktech) [inline src/test/groovy/com/vanniktech/android/junit/jacoco/ProjectHelper.groovy]: Okay then leave it there.
